language: python
python:
  - "3.7"
cache: pip
install:
  - pip install -r ./rss_feed_reader/requirements.txt
  - pip install numpy
script:
  - cd ./rss_feed_reader/tests
  - python -m unittest test_rss_feed_reader.py test_text_processing.py
  
